### ISSUE TITLE
Add option to add a prefix or suffix for some IDs

### ISSUE THREAD

**Issue by paulsbduncan** [blairconrad/dicognito#1]
It would be useful for searching on the PACS system if all the Patient IDs and AccessionNumbers, and probably StudyIDs had a prefix or suffix that was supplied when running dicognito.

I'm unsure about a separator character between the prefix/suffix and the rest of the ID. I think I'm tending towards 'leave it off' as it could be passed in as part of the prefix/suffix. Something like:

`dicognito -prefix "PD-" some.dcm`

**Comment by blairconrad** [comment]
@paulsbduncan, good suggestion. You're used to PowerShell option formats, but idiomatic python tools would start with `--`. I'm proposing `--id-prefix` and `--id-suffix`. Absolutely agree that the `-` or `:` or `—` would be considered part of the affix.

**Comment by blairconrad** [comment]
This change was released in version [0.3.0](https://github.com/blairconrad/dicognito/releases/tag/0.3.0).
