### ISSUE TITLE
Display some basic info after anonymizing file

### ISSUE THREAD

**Issue by paulsbduncan** [blairconrad/dicognito#2]
The first thing I generally want to know after anonymizing a file is how to find it. Consider adding output like this:

```
dicognito some*.dcm

Created 'anon-some1.dcm' with PatientID: ABCD1234 and AccessionNumber: EFAB5678
Created 'anon-some2.dcm' with PatientID: ABCD1234 and AccessionNumber: CDEF9012
...
```

This might be too verbose when running against a large dataset, so you could have a -q flag to suppress it.

**Comment by blairconrad** [comment]
It's a good issue. Me, I tend toward favouring quiet output over chatty and my first thought was to have a flag to _enable_ the chatter, but I could be swayed.

**Comment by paulsbduncan** [comment]
I went back and forth while creating the issue, but in the end I have a hard time envisioning when I WOULDN'T want this.

**Comment by paulsbduncan** [comment]
Also, if the file is already there from a previous 'nito, you could say 'Updated' instead of 'Created' to make it clear your overwrote a file.

**Comment by blairconrad** [comment]
Sample from 4 objects across 3 studies for 2 patients:

```
Accession Number Patient ID       Patient Name          
---------------- ----------       ------------          
Z1R8UPU88I4S     HOVJB4IHQARF     BARR^ELVIRA^DOUGLAS   
72NV46LH2UHT     TAM5FNK8WG2F     SANCHEZ^YOLANDA^ALEXIS
WQR4Z2CVDBYW     TAM5FNK8WG2F     SANCHEZ^YOLANDA^ALEXIS
```
