### ISSUE TITLE
Anonymize files in place instead of creating new ones

### ISSUE THREAD

**Issue by paulsbduncan** [blairconrad/dicognito#21]
Sometimes I want to anonymize a whole directory, throwing out what was there. This makes it easier to then store everything in this directory without worrying about file names, and it gets rid of possible confidential data from your system.

**Comment by blairconrad** [comment]
The more I think about it, the more I think it should just be the way.

**Comment by paulsbduncan** [comment]
I agree. I simplifies a lot of things, and it would be rare to not want this.
