### ISSUE TITLE
did you test your package with compatibility in Python 3 ? 

### ISSUE THREAD

**Issue by qoqoh** [blairconrad/dicognito#30]
I fell to install dicognito via pip3.

**Comment by blairconrad** [comment]
Hi @qoqoh. Thanks for your interest. I did not!
I'm new to packaging python packages (this is my first) and thought that by specifying only "Programming Language Python :: 2.7" classifier in the setup, I was signalling that it was only (so far) applicable to Python 2. (2.7, even).
Did I err?

I'm interested in supporting other versions, but haven't yet had or taken the time, other than starting to use tox for testing, which I understand will help with this. 

I was going to do this eventually, but you've prompted me to create #31. If this is something you're interested in working on, please join me over there.
