### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by blairconrad** [blairconrad/dicognito#31]
Inspired by #30.

We should support at least the latest minor, but as many as are practical, I suppose.
If it's possible to support earlier versions of Python 2 while we're at it, why not?

**Comment by qoqoh** [comment]
thank you for creating this issue. The package form pypi is older one. You could update it with newest one.

**Comment by blairconrad** [comment]
@qoqoh, I'm sorry, I don't understand. Which package from pypi is old? What problem will updating it fix?

**Comment by qoqoh** [comment]
@blairconrad You could look at this link https://pypi.org/project/dicognito/#files

**Comment by paulsbduncan** [comment]
Hi @qoqoh, the issue that @blairconrad created is still open, so you will have to wait for Python 3 support for a little while yet.

**Comment by qoqoh** [comment]
hi, @blairconrad and @paulsbduncan , thank you for your works in the supporting of python3. I am looking forward to it.

**Comment by blairconrad** [comment]
This change was released in [dicognito 0.5.0](https://github.com/blairconrad/dicognito/releases/tag/0.5.0), and is available on [PyPi](https://pypi.org/project/dicognito/).

/cc @qoqoh

**Comment by blairconrad** [comment]
This change was released in [dicognito 0.5.0](https://github.com/blairconrad/dicognito/releases/tag/0.5.0), and is available on [PyPi](https://pypi.org/project/dicognito/).

**Comment by qoqoh** [comment]
@blairconrad Many thanks for your works in the application. I will try it.
