### ISSUE TITLE
Consider warning if Burned In Annotation is YES

### ISSUE THREAD

**Issue by blairconrad** [blairconrad/dicognito#44]
If [Burned In Annation](https://dicom.innolitics.com/ciods/cr-image/general-image/00280301) is "YES", our anonymization won't be sufficient.

We could emit a WARN level log message to indicate that there are images with burned-in demographics.

If the attribute is absent, our anonymization still might not be sufficient, so we have to decide what to do about that. I suspect it's often absent, so we might want to take no action.

We could add a flag so users can customize the behaviour. For example
* never warn
* warn if Burned In Annotation is "YES"
* warn unless Burned In Annotation is "NO"

**Comment by justineclin** [comment]
Is there a way to assign this issue to me, Blair? I might have missed it.
I've not contributed to GitHub before but would like to get a chance to play with it a bit, and I'm hoping this issue could be be my ticket (ha!) to it.
Can't guarantee I'll get to it in in a particular timeframe. If later you'd like to own it back, I'd be happy to return it.
Thanks for creating this tool (looking forward to using it) and contributing!

**Comment by blairconrad** [comment]
@justineclin, I'd be happy to assign it to you. This requires that I add you as a collaborator. I've sent an invitation. Once you accept it, I can assign.

I don't think we're in a tearing rush. Don't hesitate to hoot me with any questions about 
* git
* GitHub
* Python in general
* crazy weird things I might've done in this project

**Comment by justineclin** [comment]
Thanks so much, Blair! I just accepted the invitation, as you may know
already.
Looking forward to the learning!

**Comment by justineclin** [comment]
test mention in email: @blairconrad

**Comment by justineclin** [comment]
Wow, that works, too. GitHub is magical. Sorry for the bother.
Okay, back to work. :)

**Comment by justineclin** [comment]
Here's what I'm thinking in terms of the possible values of the Burned In Annotation attributes, the different flag values we can provide and their warning behaviours, and my idea about the default. What do you think, @blairconrad ? Just to ensure I'm on the same page with you and see if you've comments/concerns.

| Attribute Value | Never | Warn if YES (Default) | Warn Unless No | Verbose |
| --------------- | ----- | --------------------- | -------------- | ------- |
| Absent          | -     | -                     | Warn           | Warn    | 
| YES             | -     | Warn                  | Warn           | Warn    |
| NO              | -     | -                     | -              | Warn    |

I'm not too attached with the Verbose mode. I thought it'd be useful for debugging purposes, but are happy to do without them. Someone like me, once I know what this flag is about, might be interested in always logging the state of the attribute. But I may not be the majority.

If this were a program, I'd even propose to make this a configuration, I assume this isn't a setting one would usually want to change. But `dicognito` is a command line tool, so I don't think configs are a good idea.

What are your thoughts of any of the above?

**Comment by blairconrad** [comment]
Thanks, @justineclin. I should've formalized options earlier. I'm generally in agreement with you. To make it more explicit, let's introduce a new command-line option: `--burned-in-annotation-warning` (it's long), with three possible values, which I'll encode in a copy of your lovely table

| Attribute Value | `never`| `if-yes` (default) | `unless-no` | 
| --------------- | ----- | --------------------- | -------------- | 
|          | -     | -                     | Warn           | 
| YES   | -     | Warn                  | Warn           | 
| NO   | -     | -                     | -              |

**Comment by justineclin** [comment]
Thanks for formalizing the options, @blairconrad. I like them. :)

I agree - let's leave out the config file/env var and the verbose option for now. If I really want it, I'll bring it up again, here or in a different issue.

I'll look to implement this, hopefully soon!

**Comment by blairconrad** [comment]
&#x1F947; Sorry for the considerable delay, @justineclin. Your contribution has been released as part of [dicognito 0.13.0](https://github.com/blairconrad/dicognito/releases/tag/0.13.0). Thanks very much for your hard work, and be sure to look for you name in the release notes!

**Comment by justineclin** [comment]
Oh! What a pleasant surprise to be mentioned in the release notes! I'm
honoured. Thanks for the note.
And you're not late given how long it took me to make the feature.
Looking forward to doing business with you again. :)

- Justin
