### ISSUE TITLE
Same patient names anonymize differently when formatted differently

### ISSUE THREAD

**Issue by paulsbduncan** [blairconrad/dicognito#78]
I had a study with multiple DICOM files. In some of the files the patient name was like 'LAST^FIRST^MIDDLE' and in others 'LAST^FIRST^MIDDLE^'. These are obviously the same patient name, but because of the trailing '^' dicognito assumed they were different and anonymized them differently.

**Comment by blairconrad** [comment]
@paulsbduncan, what do you expect the output to be, 
* 'ANONLAST^ANONFIRST^ANONMIDDLE' twice, or
* 'ANONLAST^ANONFIRST^ANONMIDDLE' and 'ANONLAST^ANONFIRST^ANONMIDDLE^'?

**Comment by paulsbduncan** [comment]
Good question! From my perspective (and current use case), either would be
fine.

**Comment by blairconrad** [comment]
Now that I'm thinking about it, we don't pay any attention to the original format anyhow. so I think you're going to get the first one!

**Comment by blairconrad** [comment]
Closed in #79. Released as part of 0.10.0.
